export enum Channels {
  startup = 'startup',
  refreshData = 'refresh-data',
  createProfile = 'create-profile',
  renameProfile = 'rename-profile',
  deleteProfile = 'delete-profile',
  login = 'login',
  logout = 'logout',
  openEditor = 'open-editor',
  closeEditor = 'close-editor',
  upsertCard = 'upsert-card',
  filter = 'filter',
  deleteCard = 'delete-card',
  getPage = 'get-page',
  openFlashcards = 'open-flashcards',
  closeBackdrop = 'close-backdrop',
  getNewCard = 'get-new-card',
  updateGraphRecord = 'update-graph-record',
  updateFlashcardsProbabilities = 'update-flashcards-probabilities',
}
